### ISSUE TITLE
Please upgrade the plugin to the latest Olly 2.0.1h

### ISSUE THREAD

**Issue by Tvangeste** [zer0fl4g/DebugDetector#1]
As of now it doesn't load into the latest Olly 2.0.1h, since the API has been updated.

**Comment by zer0fl4g** [comment]
Well, this is NOT a plugin for OllyDbg so it loads just as normal for me. Are you sure you posted the issue on the right project?

**Comment by Tvangeste** [comment]
Hehehe, sorry about that, wrong repo, it seems :)
